### ISSUE TITLE
PoPageLoginModule

### ISSUE THREAD

**Issue by dovalgomes** [portinariui/portinari-portal#1]
Fala Galera, 

Em uma tentativa de utilização do PoPageLogin em minha pagina de autenticação, seguindo a documentação disponibilizada no portinari.io, não estava conseguindo fazer funcionar de acordo com a documentação. Porem ao importar em meu módulo a PoModalPasswordRecoveryModule passou a funcionar, na documentação não especifica isso. 

Exemplo abaixo não funcionou
login.module.ts: 
`@NgModule({
  declarations: [
    LoginComponent
  ],
  imports: [
    PoModule,
    PoPageLoginModule
  ],
  exports: [
    LoginComponent,
  ]
})
export class LoginModule { }`

login.component.html
`<po-page-login></po-page-login>`

---
Exemplo abaixo funcionou
login.module.ts: 
`@NgModule({
  declarations: [
    LoginComponent
  ],
  imports: [
    PoModule,
    PoPageLoginModule,
    PoModalPasswordRecoveryModule
  ],
  exports: [
    LoginComponent,
  ]
})
export class LoginModule { }`

login.component.html
`<po-page-login></po-page-login>`

---
Dependencias da Aplicação:

` "dependencies": {
    "@angular/animations": "~8.2.8",
    "@angular/common": "~8.2.8",
    "@angular/compiler": "~8.2.8",
    "@angular/core": "~8.2.8",
    "@angular/forms": "~8.2.8",
    "@angular/platform-browser": "~8.2.8",
    "@angular/platform-browser-dynamic": "~8.2.8",
    "@angular/router": "~8.2.8",
    "@portinari/portinari-templates": "^1.9.0",
    "@portinari/portinari-ui": "^1.9.0",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.6",
    "@angular/cli": "~8.3.6",
    "@angular/compiler-cli": "~8.2.8",
    "@angular/language-service": "~8.2.8",
    "@types/jasmine": "~3.4.1",
    "@types/jasminewd2": "~2.0.7",
    "@types/node": "~12.7.8",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.4.1",
    "tslint": "~5.20.0",
    "typescript": "3.5.3"
  }`

**Comment by jhosefmarks** [comment]
Boa tarde @dovalgomes, favor abrir issue no reporitório https://github.com/portinariui/portinari-angular.
