### ISSUE TITLE
Como colaborar?

### ISSUE THREAD

**Issue by francardoso93** [portinariui/portinari-portal#2]
Pessoal, estou vendo algumas melhorias básicas que queriamos fazer via pull request, mas o único código disponível aqui é o javascript transpilado..
Alguma expectativa de compartilhar o código desse portal?

**Comment by andredealmei** [comment]
up

**Comment by mateusjmaf** [comment]
Ola @francardoso93 e @andredealmei, tudo bom?

Este repositório tem fins apenas de visualização de nossas documentações no geral.

Para darmos continuidade nesta necessidade, pedimos por gentileza que abra uma *issue* no seguinte repositório para darmos andamento ao atendimento:

https://github.com/portinariui/portinari-angular

Desde já agradecemos a compreensão.

Atenciosamente,
Mateus J. | Portinari Team
